apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: virtio-driver
spec:
  size: 1Gi
  source:
    registry:
      url: docker://quay.io/kubevirt/virtio-container-disk:latest
  diskType: cdrom
